name: console
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.9.0
  http: ^1.2.0
  dio: ^5.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
